mxonline/apps/courses/urls.py
# coding:utf-8
__author__ = 'Dylan'

from django.conf.urls import url
from .views import CoursesView, CourseDetailView, CourseInfoView, CommentsView, AddCommentView, VideoPlayView

urlpatterns = [
    url(r'^list/$', CoursesView.as_view(), name='courses_list'),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='courses_detail'),
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name='courses_info'),
    url(r'^comment/(?P<course_id>\d+)/$', CommentsView.as_view(), name='courses_comment'),
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),
    url(r'^video/$', VideoPlayView.as_view(), name='video_play'),

]

mxonline/apps/organization/urls.py
# coding:utf-8
__author__ = 'Dylan'

from django.conf.urls import url
from views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView
from views import TeacherListView, TeacherDetailView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name='org_teacher'),
    url(r'^add_fav/', AddFavView.as_view(), name='add_fav'),

    url(r'^teacher/list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

mxonline/apps/users/urls.py
# coding:utf-8
__author__ = 'Dylan'

from django.conf.urls import url
from .views import UserInfoView, UpdateImageView, UpdatePWDView, SendEmailCodeView
from .views import UpdateEmailView, MyCoursesView
from .views import MyFavOrgView, MyFavCourseView, MyFavTeacherView, MyMessageView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),
    url(r'^image/upload/$', UpdateImageView.as_view(), name='image_upload'),
    url(r'^update/pwd/$', UpdatePWDView.as_view(), name='update_pwd'),
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    url(r'^mycourses/$', MyCoursesView.as_view(), name='mycourses'),

    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name='myfav_course'),
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),
]

mxonline/mxonline/urls.py
# coding:utf-8
"""mxonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
# from django.contrib import admin
import xadmin
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModiftyView, LogoutView
from django.views.static import serve
from mxonline.settings import MEDIA_ROOT
from users.views import IndexView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    # url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='login')
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='active_user'),
    # url(r'^send_email/$', TemplateView.as_view(template_name='send_active_email.html'), name='send_active_email')
    # url(r'^send_email/$', SendEmailView.as_view(), name='send_active_email')
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<reset_code>.*)/$', ResetPwdView.as_view(), name='reset_pwd'),
    url(r'^modify/$', ModiftyView.as_view(), name='modify_pwd'),

    # 机构列表
    # url(r'^org_list/$', OrgView.as_view(), name='org_list'),
    url(r'^org/', include('organization.urls', namespace='org')),

    # 课程列表
    url(r'^courses/', include('courses.urls', namespace='courses')),

    # 机构组织列表图片
    url(r'^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT}),

    # url(r'^static/(?P<path>.*)/$', serve, {'document_root': STATIC_ROOT}),

    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^ueditor/', include('DjangoUeditor.urls')),
]

# 全局404页面
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

mxonline/apps/courses/models.py
# coding:utf-8
from __future__ import unicode_literals
from datetime import datetime

from django.db import models

# Create your models here.
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u'机构名', null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = UEditorField(verbose_name=u'课程详情', width=600, height=300, imagePath="courses/ueditor/",
                          filePath="courses/ueditor/", default='')
    degree = models.CharField(max_length=10, choices=(('cj', u'初级'), ('zj', u'中级'), ('gj', u'高级')),
                              verbose_name=u'课程难度')
    is_banner = models.BooleanField(default=False, verbose_name=u'是否轮播')
    teacher = models.ForeignKey(Teacher, verbose_name=u'讲师', null=True, blank=True)
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长（分钟）')
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name=u'封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    category = models.CharField(default=u'后端开发', max_length=20, verbose_name=u'课程类别')
    tags = models.CharField(max_length=20, verbose_name=u'课程标签', null=True, blank=True)
    need_know = models.CharField(max_length=100, verbose_name=u'课程需知', default='')
    to_learn = models.CharField(max_length=100, verbose_name=u'讲师提示', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()


class IsBannerCourse(Course):
    class Meta:
        verbose_name = u'轮播课程'
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_lesson_video(self):
        return self.video_set.all()


class Video(models.Model):
    video = models.ForeignKey(Lesson, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.CharField(default='', max_length=50, verbose_name=u'视频链接')
    study_time = models.IntegerField(default=0, verbose_name=u'学习时长（分钟）')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'资源')
    download = models.FileField(upload_to='courses/resource/%Y/%m', verbose_name=u'资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

mxonline/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>active_fail</title>
</head>
<body>
<p>用户激活失败</p>
</body>
</html>

mxonline/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block content %}

{% block bread %}
{% endblock %}

<div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banners %}
                        <li>
                            <a href="{{ banner.url }}'">
                                <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
        </div>
</div>
<!--banner end-->
<!--feature start-->
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="/static/images/feature1.png"/>
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="/static/images/feature2.png"/>
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="/static/images/feature3.png"/>
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="/static/images/feature4.png"/>
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
<div class="module">
    <div class="wp">
        <h1>公开课程</h1>
        <div class="module1 eachmod">
            <div class="module1_1 left">
                <img width="228" height="614" src="/static/images/module1_1.jpg"/>
                <p class="fisrt_word">名师授课<br/>专业权威</p>
                <a class="more" href="{% url 'courses:courses_list' %}">查看更多课程 ></a>
            </div>
            <div class="right group_list">
                <div class="module1_2 box">
                    <div class="imgslide2">
                        <ul class="imgs">
                            {% for banner_course in banner_courses %}
                            <li>
                                <a href="{% url 'courses:courses_detail' banner_course.id %}">
                                    <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="unslider-arrow2 prev"></div>
                    <div class="unslider-arrow2 next"></div>
                </div>
                {% for course in courses %}
                <div class="module1_{{ forloop.counter | add:2 }} box">
                    <a href="{% url 'courses:courses_detail' course.id %}">
                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url 'courses:courses_detail' course.id %}">
                            <h2 title="django入门">{{ course.name }}</h2>
                        </a>
                        <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                        <span class="fr">学习人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                        <span class="star fr">{{ course.fav_nums }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</section>
<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>

                            <li class="">
                                <a href="org-detail-homepage.html">
                                    <div class="company">
                                        <img width="184" height="100" src="/static/media/org/2016/11/imooc.png"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>全国知名</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="慕课网">慕课网</span></p>
                                </a>
                            </li>
                            {% for course_org in course_orgs %}
                            <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                <a href="{% url 'org:org_home' course_org.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ course_org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="北京大学">{{ course_org.name }}</span></p>
                                </a>
                            </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block custom_js %}
<script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

mxonline/templates/org-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}慕课在线学习-机构{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block current_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block current_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div class="header2 header">
 			{% if request.user.is_authenticated %}
            <div class="top">
                <div class="personal">
                    <dl class="user fr">
                        <dd>{{ request.user.name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                        <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                    </dl>
                    <div class="userdetail">
                        <dl>
                            <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            <dd>
                                <p>{{ request.user.name }}</p>
                            </dd>
                        </dl>
                        <div class="btn">
                            <a class="personcenter fl" href="{% url 'user:user_info' %}">进入个人中心</a>
                            <a class="fr" href="{% url 'logout' %}">退出</a>
                        </div>
                    </div>
                </div>
                <a href="{% url 'user:mymessage' %}">
                    <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                </a>
            </div>
        {% else %}
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->


                         <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                         <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                </div>
            </div>
        {% endif %}

            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin
                         "data-favid="22" data-fav-type="1">
                         {% if has_fav %}已收藏{% else %}收藏{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
{% block rgith_form %}
<div class="right companycenter layout grouping" >
		<div class="head">
			<h1>全部课程</h1>
			<a class="green fr more" href="org-detail-course.html">查看更多  >  </a>
		</div>
		<div class="brief group_list">

                <div class="module1_5 box">
                    <a href="course-detail.html"><img width="214" src="{% static 'media/courses/2016/11/mysql.jpg' %}"/></a>
                    <div class="des">
                        <a href="course-detail.html"><h2>django入门</h2></a>
                        <span class="fl">课时：<i class="key">0</i></span>
                        <span class="fr">参加人数：3</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">慕课网</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>

                <div class="module1_5 box">
                    <a href="course-detail.html"><img width="214" src="{% static 'media/courses/2016/11/540e57300001d6d906000338-240-135_mvvGYHL.jpg' %}"/></a>
                    <div class="des">
                        <a href="course-detail.html"><h2>django实战项目</h2></a>
                        <span class="fl">课时：<i class="key">0</i></span>
                        <span class="fr">参加人数：0</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">慕课网</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>

                <div class="module1_5 box">
                    <a href="course-detail.html"><img width="214" src="{% static 'media/courses/2016/12/python错误和异常.jpg' %}"/></a>
                    <div class="des">
                        <a href="course-detail.html"><h2>python错误和异常</h2></a>
                        <span class="fl">课时：<i class="key">0</i></span>
                        <span class="fr">参加人数：0</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">慕课网</span>
                         <span class="star fr  notlogin
                            " data-favid="13"  data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>


		</div>
	</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构教师</h1>
        <a class="green fr more" href="org-detail-teachers.html">查看更多  >  </a>
    </div>

    <div class="diarys">
        <div class="module5 share company-diary-box" style="padding:10px 0;">
            <div class="left">
                <!--<img class="pic" src=""/>-->
                <p>昵称：bobby</p>
            </div>
            <div class="right">
                <div class="top">
                    <div class="fl">
                        <a href=""><h1>java开发教程</h1></a>
                        <span>发表于：2015-10-12</span>
                    </div>
                </div>
                <div class="middle" style="border-bottom:0;">课程介绍</div>
            </div>
        </div>
    </div>



</div>
<div class="right companycenter layout" >
    <div class="head">
        <h1>机构介绍</h1>
        <a class="green fr more" href="org-detail-desc.html">查看更多  >  </a>
    </div>
    <div class="cont">&nbsp; &nbsp; <p>&nbsp; &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align:center;"><strong class="ue_t">[键入文档副标题]</strong></p><h3><span class="ue_t" style="font-family:幼圆">[标题 1]</span></h3><p class="ue_t" style="text-indent:2em;">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t" style="text-indent:2em;"><img src="../media/courses/ueditor/57aa86a0000145c512000460_20161210234050_865.jpg" title="" alt="57aa86a0000145c512000460.jpg"/> </p><h3><span class="ue_t" style="font-family:幼圆">[标题 2]</span></h3><p><img src="http://api.map.baidu.com/staticimage?center=116.410899,39.863624&zoom=11&width=530&height=340&markers=116.404,39.915" width="530" height="340"/> </p><p class="ue_t" style="text-indent:2em;">在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。 您还可以使用“开始”选项卡上的其他控件来直接设置文本格式。大多数控件都允许您选择是使用当前主题外观，还是使用某种直接指定的格式。</p><h3><span class="ue_t" style="font-family:幼圆">[标题 3]</span></h3><p>2016-12-10</p><p class="ue_t">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。 您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。 您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p><p class="ue_t"><br/> </p><p><br/></p><p><br/></p><a href="/company/desc/22/"><span class="green">[查看更多]</span></a></div>
</div>
{% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static "images" %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>